"""
pdf_gen.py — Utility for generating PDF reports from analysis results.
"""
from fpdf import FPDF
import re

class AnalysisPDF(FPDF):
    """Custom FPDF class for the Financial Analysis Report."""
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'Financial Analysis Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_pdf(analysis_text, output_path):
    """
    Converts a plain-text analysis report into a formatted PDF file.
    
    Args:
        analysis_text (str): The markdown-like text generated by the agent crew.
        output_path (str): The file path where the PDF will be saved.
    """
    import os
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    pdf = AnalysisPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=11)
    
    # Process text for basic markdown-like formatting
    lines = analysis_text.split('\n')
    for line in lines:
        # Check for Headers
        if line.startswith('### '):
            pdf.set_font("Arial", 'B', 13)
            pdf.cell(0, 10, line[4:].strip(), 0, 1)
            pdf.set_font("Arial", size=11)
        elif line.startswith('## '):
            pdf.set_font("Arial", 'B', 14)
            pdf.cell(0, 10, line[3:].strip(), 0, 1)
            pdf.set_font("Arial", size=11)
        elif line.startswith('# '):
            pdf.set_font("Arial", 'B', 16)
            pdf.cell(0, 10, line[2:].strip(), 0, 1)
            pdf.set_font("Arial", size=11)
        # Check for Bullet Points
        elif line.startswith('* ') or line.startswith('- '):
            pdf.multi_cell(0, 8, f'  • {line[2:].strip()}')
        # Regular text
        else:
            if line.strip() == "":
                pdf.ln(5)
            else:
                # Basic multi-line support
                pdf.multi_cell(0, 8, line)

    pdf.output(output_path)
    return output_path
